import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TopNav from "@/components/TopNav";
import Sidebar from "@/components/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* ใช้ h-screen และ overflow-hidden เพื่อไม่ให้ Scrollbar ซ้อนกันมั่ว */}
      <body className="flex h-screen bg-gray-50 overflow-hidden">
        
        {/* --- ส่วนที่ 1: Sidebar (ซ้าย) --- */}
        {/* ไม่ต้องกำหนด width ที่นี่ เพราะ Sidebar จัดการตัวเองแล้ว */}
        <Sidebar />

        {/* --- ส่วนที่ 2: พื้นที่ขวาทั้งหมด (Wrapper) --- */}
        <div className="flex-1 flex flex-col min-w-0">
          
          {/* 2.1 Navbar (บน) */}
          <TopNav />

          {/* 2.2 เนื้อหาหลัก (ล่าง) */}
          {/* ใส่ overflow-y-auto เพื่อให้ Scroll ได้แค่ตรงเนื้อหา Sidebar กับ Navbar จะอยู่นิ่งๆ */}
          <main className="flex-1 overflow-y-auto ">
            {children}
          </main>

        </div>
        
      </body>
    </html>
  );
}
